version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017 
    ports:
      - "5000:80"  
      - "5001:443"
    depends_on:
      - mongo  
    volumes:
      - ./logs:/app/logs  

  mongo:
    image: mongo:4.4
    container_name: chat_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data:

